version: "3.7"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetworks

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - :5432
    networks:
      - djangonetworks
    restart: always

networks:
  djangonetworks:
    driver: bridge
