version: "3.7"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - djangonetworks

  db:
    image: mysql:8.2.0
    container_name: my-mysql-container
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./.env.dev
    environment:
      - MYSQL_DATABASE='storefront'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='Karnob@711'
      - MYSQL_HOST='localhost'
      - MYSQL_ROOT_PASSWORD='Karnob@711'
    ports:
      - :3306
    networks:
      - djangonetworks
    restart: always

networks:
  djangonetworks:
    driver: bridge
